version: '3.4'

services:
  ansible:
    image: williamyeh/ansible:alpine3
    volumes:
      - ./deploy/:/projects
    working_dir: /projects
    command: ./deploy.sh ansible production site.yml --check
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
