source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2', '>= 5.2.1'
# Use Puma as the app server
gem 'puma', '~> 3.12'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.3', '>= 1.3.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

gem 'tzinfo-data', '~> 1.2018', '>= 1.2018.7'

gem 'http', '~> 4.0'
gem 'license_finder', '~> 5.5', '>= 5.5.2'

group :development do
  gem 'rubocop', '~> 0.60.0', require: false
end

group :test do
  gem 'simplecov', '~> 0.16.1', require: false
  gem 'webmock', '~> 3.4', '>= 3.4.2'
end
